[pymunk_field]
dt = 0.016666666 # 60 fps
microsteps = 70

[car]
position = [0.5, 3.5]
sensors = [
	{x = -0.06, y = 0.14, angle = -90, range_ = 2, beam_width = 0.001},
	{x = -0.05, y = 0.14, angle = 0, range_ = 2, beam_width = 0.001},
	{x = -0.03, y = 0.14, angle = 45, range_ = 2, beam_width = 0.001},
	{x = 0.03, y = 0.14, angle = -45, range_ = 2, beam_width = 0.001},
	{x = 0.05, y = 0.14, angle = 0, range_ = 2, beam_width = 0.001},
	{x = 0.06, y = 0.14, angle = 90, range_ = 2, beam_width = 0.001},
]

wheel_radius = 0.035
wheel_width = 0.020
wheel_mass = 0.01
wheel_slipforce = 60
wheel_friction_force = 30
wheel_side_friction = 0.5
wheel_weird_forward_friction = 0.01

front_wheels_x = 0.04
front_wheels_y = 0.20
back_wheels_x = 0.04
back_wheels_y = 0.20

car_width = 0.015
car_height = 0.0185
car_mass = 0.4
max_steer_angle = 45
max_speed = 6
max_power = 40
hull_friction = 0.8

[circle]
mass = 1.1
radius = 0.15
elasticity = 0.99

[walls]
thickness = 0.01
elasticity = 0.999
walls = [
            [[0, 0], [0, 4]],
            [[0, 4], [9, 4]],
            [[9, 4], [9, 2]],
            [[7, 2], [9, 2]],
            [[7, 0], [7, 2]],
            [[4, 0], [7, 0]],
            [[4, 0], [4, 2]],
            [[3, 2], [4, 2]],
            [[3, 0], [3, 2]],
            [[3, 0], [3, 2]],
            [[0, 0], [3, 0]],
            [[1, 1], [2, 1]],
            [[1, 1], [1, 3]],
            [[2, 1], [2, 3]],
            [[5, 1], [6, 1]],
            [[5, 1], [5, 3]],
            [[6, 1], [6, 3]],
            [[1, 3], [8, 3]],
]

[checkpoints]
detection_radius = 0.5
checkpoints = [
    [0.5, 2.5],
    [1.5, 0.5],
    [2.5, 1.5],
    [3.5, 2.5],
    [4.5, 1.5],
    [5.5, 0.5],
    [6.5, 1.5],
    [7.5, 2.5],
    [8.5, 3.0],
    [7.5, 3.5],
    [1.5, 3.5],
]
